name: CI Alerta ntfy Python

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ejecutar script de Python
        run: python main.py

      - name: Enviar notificación a ntfy.sh
        run: |
          curl -H "Title: GitHub Actions - ITLA ✅" \
               -H "Tags: white_check_mark,rocket,github,devops" \
               -d "¡Nuevo código subido con éxito a la rama main!
          
          👤 Autor: ${{ github.actor }}
          💬 Commit: ${{ github.event.head_commit.message }}" \
          ntfy.sh/devops-itla